name: push hotfix

on:
  push:
    branches:
      - 'hotfix*'

env:
  GIT_USER_EMAIL: "actions@github.com"
  GIT_USER_NAME: "GitHub Actions"
  CURRENT_BRANCH: ${{ github.event.ref }}

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git identity
        run: |
          git config --global user.email "${{ env.GIT_USER_EMAIL }}"
          git config --global user.name "${{ env.GIT_USER_NAME }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
        id: build
        if: success()

      - name: Run Unit Tests
        run: ./gradlew runUnitTests
        if: success()

      - name: Run Integration Tests
        run: ./gradlew runIntegrationTests
        if: success()

      - name: Merge test into dev and main
        run: |
          git checkout dev
          git merge "${CURRENT_BRANCH}"
          git checkout main
          git merge "${CURRENT_BRANCH}"
        if: success()

      - name: delete hotfix branch
        run: |
          git branch -D "${CURRENT_BRANCH}"
        if: success()

      - name: Build & push Docker image
        id: docker
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: "${{ env.DOCKER_IMAGE_NAME }}"
          tags: "latest"
          registry: "${{ env.DOCKER_REGISTRY }}"
          dockerfile: Dockerfile
          username: "${{ env.DOCKER_USERNAME }}"
          password: "${{ env.DOCKER_PASSWORD }}"

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: "${{ env.DISCORD_WEBHOOK }}"
        uses: Ilshidur/action-discord@master
        with:
          args: '{{ env.DOCKER_IMAGE_TAGS }} Version of {{ EVENT_PAYLOAD.repository.full_name }} is now available!'
